model_configs:
  peft_type: "lora"
  task_type: "seq_cls"
  model_name_or_path: "chaoyi-wu/PMC_LLAMA_7B"
  peft_hyperparameters:
    method: bayes
    metric:
      name: val_roc_auc
      goal: maximize
    parameters:
      r:
        values: [8, 16]
      lora_alpha:
        values: [16, 32]
      lora_dropout: 
        values: [0.0, 0.1, 0.2]
  model_hyperparameters:
    learning_rate: 0.00005
    warmup_steps_ratio: 0.06
    max_seq_len: 128
    gradient_accumulation_steps: 2
training_configs:
  dataset_paths:
    - aryopg/trec-pmv
  random_seed: 1234
  device: 0
  num_process: 8
  test_size: 0.1
  epochs: 10
  steps: 1000000
  batch_size: 10
  log_steps: 1000000
  eval_steps: 1000000  # Only evaluate at the end
  checkpoint_steps: 1000000  # Only checkpoint at the end
  max_sweep_count: 20
  outputs_dir: "outputs"
