model_configs:
  peft_type: "lora"
  task_type: "causal_lm"
  model_name_or_path: "meta-llama/Llama-2-7b-hf"
  peft_hyperparameters:
    method: bayes
    metric:
      name: eval_ppl
      goal: minimize
    parameters:
      r:
        values: [2, 4, 8, 16]
      lora_alpha:
        values: [4, 8, 16, 32]
      lora_dropout: 
        values: [0.0, 0.1, 0.2]
  model_hyperparameters:
    learning_rate: 0.0003
    warmup_steps_ratio: 0.06
    max_seq_len: 512
    gradient_accumulation_steps: 4
training_configs:
  dataset_paths:
    - aryopg/mimic-combined
  random_seed: 1234
  device: 0
  num_process: 8
  test_size: 0.1
  epochs: 1
  steps: 1000000
  batch_size: 10
  log_steps: 100
  eval_steps: 1000000  # Only evaluate at the end
  checkpoint_steps: 1000000  # Only checkpoint at the end
  max_sweep_count: 20
  outputs_dir: "outputs"
