name: clinical_peft
channels:
  - defaults
  - nvidia
  - pytorch
  - huggingface
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - torchvision
  - torchaudio
  - pytorch
  - pytorch-cuda=11.8
  - datasets
  - transformers
  - evaluate
  - huggingface_hub
  - isort
  - sentencepiece
  - pandas
  - python-dotenv
  - pydantic
  - wandb
  - black
  - matplotlib
  - scikit-learn
  - tqdm
  - accelerate
  - pip:
    - tokenizers
    - -e ./submodules/peft