model_configs:
  peft_type: "adaptation_prompt_tuning"
  task_type: "causal_lm"
  model_name_or_path: "meta-llama/Llama-2-7b-hf"
  peft_hyperparameters:
    method: grid
    metric:
      name: eval_ppl
      goal: minimize
    parameters:
      adapter_len:
        values: [5, 10]
      adapter_layers: 
        values: [10, 20, 30]
  model_hyperparameters:
    learning_rate: 0.0003
    warmup_steps_ratio: 0.06
    max_seq_len: 512
    gradient_accumulation_steps: 64
training_configs:
  dataset_paths:
    - aryopg/mimic-iv
  random_seed: 1234
  device: 0
  num_process: 8
  test_size: 0.1
  epochs: 1
  steps: 1000000
  batch_size: 8
  log_steps: 100
  eval_steps: 1000000
  checkpoint_steps: 1000000  # Only checkpoint at the end
  max_sweep_count: 20
  outputs_dir: "outputs"
