model_configs:
  peft_type: "lora"
  task_type: "causal_lm"
  model_name_or_path: "aryopg/llama-7b"
  peft_hyperparameters:
    r: 8
    lora_alpha: 32
    lora_dropout: 0.1
    bias: "none"
  model_hyperparameters:
    learning_rate: 0.001
    max_seq_len: 128
    gradient_accumulation_steps: 4
training_configs:
  dataset_paths:
    - aryopg/mini-mimic-iv
  random_seed: 1234
  device: 0
  num_process: 8
  test_size: 0.1
  steps: 1000000
  batch_size: 8
  eval_steps: 100
  checkpoint_steps: 10000
  outputs_dir: "outputs"
