model_configs:
  peft_type: "lora"
  task_type: "causal_lm"
  model_name_or_path: "aryopg/llama-7b"
  peft_hyperparameters:
    method: bayes
    metric:
      name: eval_ppl
      goal: minimize
    parameters:
      encoder_reparameterization_type:
        values: ["MLP", "LSTM"]
      encoder_hidden_size: 
        values: [2]
      encoder_num_layers:
        values: [2]
      encoder_dropout: 
        values: [0.0]
  model_hyperparameters:
    learning_rate: 0.0003
    max_seq_len: 128
    gradient_accumulation_steps: 4
training_configs:
  dataset_paths:
    - aryopg/mimic-iv
  random_seed: 1234
  device: 0
  num_process: 8
  test_size: 0.1
  steps: 1000000
  batch_size: 8
  eval_steps: 100
  checkpoint_steps: 1000000  # Only checkpoint at the end
  max_sweep_count: 20
  outputs_dir: "outputs"
